#!/bin/bash

# Source the configuration
. ./tstatconf.inc

# Source the database configuration
. ./tstatdb.inc

# Source the API Implementation
. ./tstatapi.inc

# Basic Info
MAINTEMP=`readThermSensorTemp Local`
HVACMODE=`readThermHvacMode`
HVACSTATE=`readThermHvacState`
FANMODE=`readThermFanMode`
AVGTEMP=`readThermAverageTemp`
HEATSETPOINT=`readThermSetbackHeat`
COOLSETPOINT=`readThermSetbackCool`
SETBACKSTATUS=`readThermSetbackStatus`
sleep 5

# Remote Sensors
RS1STATE=`readThermSensorState RS1`
if [ $RS1STATE = "Enabled" ]; then
  RS1TEMP=`readThermSensorTemp RS1`
else
  RS1TEMP=0
fi
RS2STATE=`readThermSensorState RS2`
if [ $RS2STATE = "Enabled" ]; then
  RS2TEMP=`readThermSensorTemp RS2`
else
  RS2TEMP=0
fi
sleep 5

# Alarms
LOWTEMPALARM=`readCommonAlarmStatus LowTemp`
HIGHTEMPALARM=`readCommonAlarmStatus HighTemp`
FILTERALARM=`readCommonAlarmStatus Filter`

# Schedule
SCHEDPERIOD=`readThermCurrentPeriod`
SCHEDCLASS=`readThermCurrentClass`
ACTIVEPERIOD=`readThermActivePeriod`
sleep 5

QUERY="INSERT INTO tstat_tracking VALUES (0,NOW(),$MAINTEMP,\"$RS1STATE\",$RS1TEMP,\"$RS2STATE\",$RS2TEMP,$AVGTEMP,$HEATSETPOINT,$COOLSETPOINT,\"$SETBACKSTATUS\",\"$HVACMODE\",\"$HVACSTATE\",\"$FANMODE\",\"$SCHEDCLASS\",\"$SCHEDPERIOD\",\"$ACTIVEPERIOD\",\"$LOWTEMPALARM\",\"$HIGHTEMPALARM\",\"$FILTERALARM\");"

echo $QUERY | mysql -h $DBHOST -u $DBUSER -p${DBPSWD} $DBNAME

# EOF
